### PR TITLE
Include proper schemas for our example types

### LINKED ISSUE #435: Infinite empty conditions
Steps to reproduce

```
git clone https://github.com/knative-sandbox/sample-controller && cd sample-controller/
KO_DOCKER_REPO=kind.local ko apply -f config/
ko apply -f example-addressable-service.yaml
kubectl get addressableservices.samples.knative.dev -n knative-samples make-it-addressable -oyaml
```

results in:
```yaml
...
spec:
  serviceName: webhook
status:
  address:
    url: http://webhook.knative-samples.svc.cluster.local
  conditions:
  - {}
  - {}
  - {}
  - {}
...
```

It seems to constantly re-add a new empty condition:

```
$ kubectl get addressableservices.samples.knative.dev -n knative-samples make-it-addressable -oyaml | wc -l
     377
$ kubectl get addressableservices.samples.knative.dev -n knative-samples make-it-addressable -oyaml | wc -l
     381
```

...and so on.

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes #435

### CODE REVIEW

**Comment by dprotaso** [comment]
/assign @markusthoemmes 

cc @imjasonh

**Comment by imjasonh** [comment]
This helps with consuming the sample, but doesn't do much to help when modifying the sample for my own needs (renaming the type, adding a field, etc.).

Can we include/document the CRD-generation script in the repo as well?

**Comment by markusthoemmes** [comment]
I think we might want to generalize the generation script towards `hack` and then have that here. We're not _quite_ there yet.

**Comment by dprotaso** [comment]
Create an issue https://github.com/knative-sandbox/sample-controller/issues/470

**Review by markusthoemmes — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
